title: Xinran Xu # your name (or website title) here
logo: "/images/Photo.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Business Analyst - Simon Business School,University of Rochester
  <br><br>
  Proficient in MS Office, SQL, RStudio, and Tableau.
  <br><br>
  <a href="https://www.linkedin.com/in/xinranxu1/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal

